### ISSUE TITLE
Session ID is coming as null ,

### ISSUE THREAD

**Issue by automatenew** [cmccarthyIrl/spring-cucumber-testng-parallel-test-harness#4]
Set the parallel to false for single thread execution 

public class WeatherRunnerTest extends AbstractTestNGCucumberTests {
    @Override
    @DataProvider(parallel = false)
    public Object[][] scenarios() {
        return super.scenarios();
    }

[INFO]   Run 1: PASS
[ERROR]   Run 2: WikipediaParallelRunnerTest.runScenario » NoSuchSession Session ID is null. Us...
[ERROR]   Run 3: WikipediaParallelRunnerTest.runScenario » NoSuchSession Session ID is null. Us...

how to limit the number of threads, please let me know.  

Thanks for the greater work

**Comment by cmccarthyIrl** [comment]
`WebDriverRunner` is closing the drivers session after each test when `parallel = false`. The `Selanide` dependency should be removed and replaced with `driverThreadLocal` instance, in the `DriverManger.class`.  Feel free to open a PR if you fix it.

**Comment by cmccarthyIrl** [comment]
Have a look at this commit : https://github.com/cmccarthyIrl/spring-cucumber-testng-parallel-test-harness/tree/b55a071801d4b7240ad077544bdd98c6908d3aaa/wikipedia/src/test/java/com/cmccarthy/ui
